name: CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [18]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci

      - name: Bootstrap CDK
        run: |
          npm run bootstrap
    
      - name: Deploy CDK App
        run: |
          npm run deploy
